# -*- coding: utf-8 -*-
"""ai_coba3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13WcjmfmlIYKp7meozIvbSv2o4Mprsz51

# Final Project - Explainable Deep Learning for Potentially Hazardous Asteroids Identification Using Sequential Orbital Parameters under Extreme Class Imbalance

| Fitur (Nama Kolom) | Definisi                             | Keterangan                                                                                                                               |
| :----------------- | :----------------------------------- | :--------------------------------------------------------------------------------------------------------------------------------------- |
| **spkid**          | ID unik objek                        | Nomor identifikasi unik asteroid dalam basis data astronomi.                                                                             |
| **targetname**     | Nama target                          | Nama atau identitas asteroid yang digunakan dalam pengamatan dan analisis.                                                               |
| **datetime_jd**    | Waktu pengamatan (Julian Date)       | Tanggal dan waktu observasi yang dinyatakan dalam format Julian Date (JD), umum digunakan dalam astronomi.                               |
| **e**              | Eksentrisitas orbit                  | Menggambarkan bentuk orbit asteroid; nilai 0 menunjukkan orbit melingkar, sedangkan nilai mendekati 1 menunjukkan orbit semakin lonjong. |
| **a**              | Semi-major axis                      | Jarak rata-rata asteroid terhadap Matahari dalam orbitnya, biasanya dinyatakan dalam Astronomical Unit (AU).                             |
| **incl**           | Inklinasi orbit                      | Sudut kemiringan orbit asteroid terhadap bidang ekliptika atau bidang orbit Bumi (dalam derajat).                                        |
| **q**              | Perihelion distance                  | Jarak terdekat asteroid ke Matahari selama pergerakannya dalam orbit.                                                                    |
| **M**              | Mean anomaly                         | Posisi asteroid dalam orbitnya pada waktu tertentu, dinyatakan dalam derajat.                                                            |
| **pha**            | Potentially Hazardous Asteroid (PHA) | Indikator yang menunjukkan apakah asteroid dikategorikan berpotensi berbahaya bagi Bumi (`Y` = Ya, `N` = Tidak).                         |
| **H**              | Magnitudo absolut                    | Tingkat kecerahan intrinsik asteroid; semakin kecil nilainya, semakin terang dan umumnya semakin besar ukuran asteroid.                  |
| **diameter**       | Diameter asteroid                    | Ukuran fisik asteroid, umumnya dinyatakan dalam kilometer (km).                                                                          |
| **albedo**         | Reflektivitas                        | Kemampuan permukaan asteroid memantulkan cahaya Matahari, dengan rentang nilai antara 0 hingga 1.                                        |
| **moid**           | Minimum Orbit Intersection Distance  | Jarak minimum antara orbit asteroid dan orbit Bumi; digunakan untuk menilai potensi risiko tumbukan dengan Bumi.                         |

# Import Library
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

from sklearn.model_selection import GroupShuffleSplit
from sklearn.preprocessing import RobustScaler, LabelEncoder
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score, average_precision_score, precision_recall_curve

import tensorflow as tf
from tensorflow.keras.models import Sequential, Model
from tensorflow.keras.layers import Input, Dense, LSTM, Bidirectional, Dropout, GRU, LayerNormalization, MultiHeadAttention, GlobalAveragePooling1D
from tensorflow.keras.callbacks import EarlyStopping
from sklearn.utils.class_weight import compute_class_weight
import shap

"""# Load Dataset

## Crawling Time-Series Data from JPL Horizons API
"""

!pip install astroquery pandas

import pandas as pd
from astroquery.jplhorizons import Horizons
import time

# 2. Siapkan daftar SPK-ID
list_spk_id = [
    # --- KELOMPOK 1: NEO & PHA Terkenal (20 Asteroid) ---
    '4179', '99942', '101955', '162173', '29075', '54509', '65803', '136617', '153814', '341843', # PHA (Berbahaya)
    '433', '719', '887', '1036', '1221', '1566', '1620', '1862', '2062', '3200',                # NEO (Dekat Bumi)

    # --- KELOMPOK 2: Main Belt Asteroids (Urutan 1 - 140) ---
    '1', '2', '3', '4', '5', '6', '7', '8', '9', '10',
    '11', '12', '13', '14', '15', '16', '17', '18', '19', '20',
    '21', '22', '23', '24', '25', '26', '27', '28', '29', '30',
    '31', '32', '33', '34', '35', '36', '37', '38', '39', '40',
    '41', '42', '43', '44', '45', '46', '47', '48', '49', '50',
    '51', '52', '53', '54', '55', '56', '57', '58', '59', '60',
    '61', '62', '63', '64', '65', '66', '67', '68', '69', '70',
    '71', '72', '73', '74', '75', '76', '77', '78', '79', '80',
    '81', '82', '83', '84', '85', '86', '87', '88', '89', '90',
    '91', '92', '93', '94', '95', '96', '97', '98', '99', '100',
    '101', '102', '103', '104', '105', '106', '107', '108', '109', '110',
    '111', '112', '113', '114', '115', '116', '117', '118', '119', '120',
    '121', '122', '123', '124', '125', '126', '127', '128', '129', '130',
    '131', '132', '133', '134', '135', '136', '137', '138', '139', '140',

    # --- KELOMPOK 3: Asteroid Penyeimbang / Pelengkap (Urutan 141 - 280) ---
    '141', '142', '143', '144', '145', '146', '147', '148', '149', '150',
    '151', '152', '153', '154', '155', '156', '157', '158', '159', '160',
    '161', '162', '163', '164', '165', '166', '167', '168', '169', '170',
    '171', '172', '173', '174', '175', '176', '177', '178', '179', '180',
    '181', '182', '183', '184', '185', '186', '187', '188', '189', '190',
    '191', '192', '193', '194', '195', '196', '197', '198', '199', '200',
    '201', '202', '203', '204', '205', '206', '207', '208', '209', '210',
    '211', '212', '213', '214', '215', '216', '217', '218', '219', '220',
    '221', '222', '223', '224', '225', '226', '227', '228', '229', '230',
    '231', '232', '233', '234', '235', '236', '237', '238', '239', '240',
    '241', '242', '243', '244', '245', '246', '247', '248', '249', '250',
    '251', '252', '253', '254', '255', '256', '257', '258', '259', '260',
    '261', '262', '263', '264', '265', '266', '267', '268', '269', '270',
    '271', '272', '273', '274', '275', '276', '277', '278', '279', '280'
]

semua_data = []

start_time = '2016-06-01'
end_time = '2026-06-01'
step_size = '30d'

print(f"Memulai proses crawling untuk {len(list_spk_id)} asteroid...")

# 3. Looping Crawling
for spkid in list_spk_id:
    print(f"Mengambil data historis SPK-ID: {spkid}...")
    try:
        obj = Horizons(id=spkid,
                       location='500@10',
                       epochs={'start': start_time, 'stop': end_time, 'step': step_size},
                       id_type='smallbody')

        df_temp = obj.elements().to_pandas()
        df_temp['spkid'] = spkid

        kolom_penting = ['spkid', 'targetname', 'datetime_jd', 'e', 'a', 'incl', 'q', 'node', 'argper', 'M']
        kolom_tersedia = [col for col in kolom_penting if col in df_temp.columns]

        df_bersih = df_temp[kolom_tersedia]
        semua_data.append(df_bersih)

        # Jeda agar tidak diblokir NASA
        time.sleep(1.5)

    except Exception as e:
        print(f"[-] Gagal mengambil data {spkid}. Error: {e}")

# 4. Satukan data dan SAVE LANGSUNG KE G-DRIVE
if semua_data:
    df_final = pd.concat(semua_data, ignore_index=True)

    lokasi_save = '/content/drive/MyDrive/Kuliah/sem6/AITerapan/FinalProject/dataset/asteroid_timeseries.csv'

    df_final.to_csv(lokasi_save, index=False)

    print("\n=======================================================")
    print(f"SELESAI! Data berhasil disimpan di Google Drive kakak.")
    print(f"Lokasi: {lokasi_save}")
    print(f"Total baris: {len(df_final)}")
    print("=======================================================")
else:
    print("\nTidak ada data yang berhasil diambil.")

import pandas as pd
df1 = pd.read_csv('/content/drive/MyDrive/Kuliah/sem6/AITerapan/FinalProject/dataset/asteroid_timeseries.csv')

df1.info()

df1.head()

"""## Static Data from JPL Small Database"""

import pandas as pd
df2 = pd.read_csv('/content/drive/MyDrive/Kuliah/sem6/AITerapan/FinalProject/dataset/asteroid_awal.csv')

df2.info()

df2.head()

"""## Merge Data"""

import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/Kuliah/sem6/AITerapan/FinalProject/dataset/asteroid_timeseries.csv')

df['spkid'] = df['spkid'].astype(int) + 20000000 #format resmi fr NASA

df_final = pd.merge(df, df2, on='spkid', how='left')

print("Info dataset final:")
df_final.info()

print("\nCuplikan data Toutatis dan kawan-kawan yang sudah sukses terisi:")
print(df_final[['spkid', 'targetname', 'H', 'diameter', 'moid', 'pha']].head())

df_final.to_csv('/content/drive/MyDrive/Kuliah/sem6/AITerapan/FinalProject/dataset/asteroid_fiks.csv', index=False)

import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/Kuliah/sem6/AITerapan/FinalProject/dataset/asteroid_fiks.csv')

"""# EDA

## info dataset
"""

df.info()
df.describe(include='all')

"""## missing value"""

print(df.isnull().sum())

"""## duplicate"""

print('Duplicates:', df.duplicated().sum())

"""## class distribution"""

plt.figure(figsize=(6,4))
sns.countplot(data=df, x='pha')
plt.title('PHA Class Distribution (Extreme Imbalance)')
plt.show()

"""## sequence length distribution"""

seq_length = df.groupby('spkid').size()
print("\n--- Sequence Length Distribution ---")
print(seq_length.describe())

"""## numeric distribution"""

numerical_cols = ['e', 'a', 'incl', 'q', 'M', 'H', 'diameter', 'albedo', 'moid']
df[numerical_cols].hist(figsize=(15, 10), bins=30)
plt.suptitle('Numerical Distribution')
plt.show()

"""## correlation analysis"""

tmp=df.copy()
tmp['pha']=tmp['pha'].map({'N':0,'Y':1})
corr=tmp[numerical_cols+['pha']].corr()
plt.figure(figsize=(10,8))
sns.heatmap(corr,annot=True,cmap='coolwarm')
plt.show()

"""## orbit visualization"""

orb=df.groupby('spkid').agg({'q':'mean','moid':'mean','pha':'first'}).reset_index()
sns.scatterplot(data=orb,x='q',y='moid',hue='pha')
plt.show()

"""# Preprocessing

## handle missing value
"""

df[numerical_cols] = df.groupby('spkid')[numerical_cols].transform(lambda x: x.interpolate(method='linear', limit_direction='both'))

df[numerical_cols] = df[numerical_cols].fillna(df[numerical_cols].median())

df.isnull().sum()

"""## label target encode"""

le = LabelEncoder()
df['pha'] = le.fit_transform(df['pha'])

print(df['pha'].unique())

"""## Train/Val/Test Split by Asteroid"""

gss1 = GroupShuffleSplit(n_splits=1, test_size=0.2, random_state=42)
train_val_idx, test_idx = next(gss1.split(df, groups=df['spkid']))
df_train_val = df.iloc[train_val_idx]
df_test = df.iloc[test_idx]

gss2 = GroupShuffleSplit(n_splits=1, test_size=0.25, random_state=42) # 0.25 dari 0.8 = 0.2 keseluruhan
train_idx, val_idx = next(gss2.split(df_train_val, groups=df_train_val['spkid']))
df_train = df_train_val.iloc[train_idx]
df_val = df_train_val.iloc[val_idx]

"""## Feature Engineering"""

for d in [train_df,val_df,test_df]:
    d['e_change']=d.groupby('spkid')['e'].diff().fillna(0)
    d['a_change']=d.groupby('spkid')['a'].diff().fillna(0)
    d['M_change']=d.groupby('spkid')['M'].diff().fillna(0)
    d['q_a_ratio']=d['q']/d['a']

FEATURES=['e','a','incl','q','M','H','diameter','albedo','moid',
          'e_change','a_change','M_change','q_a_ratio']

"""## scaling"""

scaler = RobustScaler()
df_train[numerical_cols] = scaler.fit_transform(df_train[numerical_cols])
df_val[numerical_cols] = scaler.transform(df_val[numerical_cols])
df_test[numerical_cols] = scaler.transform(df_test[numerical_cols])

"""# Sequence Construction"""

def create_sequences(data, feature_cols, target_col, timesteps=122):
    sequences, labels = [], []
    for _, group in data.groupby('spkid'):
        seq = group[feature_cols].values
        label = group[target_col].values[0] # Ambil 1 label target karena targetnya level asteroid

        # Zero padding jika sequence kurang dari timesteps
        if len(seq) >= timesteps:
            sequences.append(seq[-timesteps:])
        else:
            pad_len = timesteps - len(seq)
            pad_array = np.zeros((pad_len, len(feature_cols)))
            sequences.append(np.vstack((pad_array, seq)))
        labels.append(label)
    return np.array(sequences), np.array(labels)

TIMESTEPS = int(seq_length.median()) # sekitar 122
X_train, y_train = create_sequences(df_train, numerical_cols, 'pha', TIMESTEPS)
X_val, y_val = create_sequences(df_val, numerical_cols, 'pha', TIMESTEPS)
X_test, y_test = create_sequences(df_test, numerical_cols, 'pha', TIMESTEPS)

print(f"Shape X_train: {X_train.shape}")

"""## Extreme Imbalance Handling"""

weights = compute_class_weight(class_weight='balanced', classes=np.unique(y_train), y=y_train)
class_weights = dict(enumerate(weights))

def focal_loss(gamma=2., alpha=0.25):
    def focal_loss_fixed(y_true, y_pred):
        y_true = tf.cast(y_true, tf.float32)
        y_pred = tf.clip_by_value(y_pred, tf.keras.backend.epsilon(), 1 - tf.keras.backend.epsilon())
        alpha_t = y_true * alpha + (1 - y_true) * (1 - alpha)
        p_t = y_true * y_pred + (1 - y_true) * (1 - y_pred)
        fl = - alpha_t * tf.math.pow((1 - p_t), gamma) * tf.math.log(p_t)
        return tf.reduce_mean(fl)
    return focal_loss_fixed

"""# DeepLearning Models"""

input_shape = (X_train.shape[1], X_train.shape[2])

"""# LSTM"""

def build_lstm():
    model = Sequential([
        Input(shape=input_shape),
        LSTM(64, return_sequences=True), Dropout(0.3),
        LSTM(32), Dropout(0.3),
        Dense(16, activation='relu'),
        Dense(1, activation='sigmoid')
    ])
    model.compile(optimizer='adam', loss=focal_loss(), metrics=['accuracy', tf.keras.metrics.AUC(name='pr_auc', curve='PR')])
    return model

"""# BiLSTM"""

def build_bilstm():
    model = Sequential([
        Input(shape=input_shape),
        Bidirectional(LSTM(64, return_sequences=True)), Dropout(0.3),
        Bidirectional(LSTM(32)), Dropout(0.3),
        Dense(16, activation='relu'),
        Dense(1, activation='sigmoid')
    ])
    model.compile(optimizer='adam', loss=focal_loss(), metrics=['accuracy', tf.keras.metrics.AUC(name='pr_auc', curve='PR')])
    return model

"""# GRU"""

def build_gru():
    model = Sequential([
        Input(shape=input_shape),
        GRU(64, return_sequences=True), Dropout(0.3),
        GRU(32), Dropout(0.3),
        Dense(16, activation='relu'),
        Dense(1, activation='sigmoid')
    ])
    model.compile(optimizer='adam', loss=focal_loss(), metrics=['accuracy', tf.keras.metrics.AUC(name='pr_auc', curve='PR')])
    return model

"""# Transformer Encoder"""

# Model 4: Transformer Encoder (Self-Attention untuk Orbital Parameters)
def build_transformer():
    inputs = Input(shape=input_shape) # Bentuk awal: (None, 122, 9)

    # 1. Projection Layer (Wajib agar dimensi seragam untuk Residual Connection)
    d_model = 64
    x = Dense(d_model)(inputs) # Mengubah fitur dari 9 menjadi 64 -> (None, 122, 64)

    # 2. Self Attention Block
    # key_dim diatur sama dengan d_model
    attn_output = MultiHeadAttention(key_dim=d_model, num_heads=4)(x, x)
    attn_output = Dropout(0.2)(attn_output)
    # Residual connection: 64 + 64 (Aman)
    x = LayerNormalization(epsilon=1e-6)(x + attn_output)

    # 3. Feed Forward Block
    # Ekspansi dimensi lalu proyeksikan kembali ke d_model
    x_ff = Dense(128, activation='relu')(x)
    x_ff = Dense(d_model)(x_ff)
    x_ff = Dropout(0.2)(x_ff)
    # Residual connection: 64 + 64 (Aman)
    x = LayerNormalization(epsilon=1e-6)(x + x_ff)

    # 4. Aggregation & Output
    x = GlobalAveragePooling1D()(x)
    x = Dense(16, activation='relu')(x)
    outputs = Dense(1, activation='sigmoid')(x)

    model = Model(inputs=inputs, outputs=outputs)
    model.compile(optimizer='adam', loss=focal_loss(), metrics=['accuracy', tf.keras.metrics.AUC(name='pr_auc', curve='PR')])
    return model

"""# Training"""

early_stopping = EarlyStopping(monitor='val_pr_auc', mode='max', patience=15, restore_best_weights=True)

# Ganti dengan model pilihan (build_lstm(), build_bilstm(), build_gru(), atau build_transformer())
model = build_lstm()
print("\n--- Training Model ---")
history = model.fit(
    X_train, y_train,
    validation_data=(X_val, y_val),
    epochs=100,
    batch_size=32,
    class_weight=class_weights,
    callbacks=[early_stopping],
    verbose=1
)

early_stopping = EarlyStopping(monitor='val_pr_auc', mode='max', patience=15, restore_best_weights=True)

# Ganti dengan model pilihan (build_lstm(), build_bilstm(), build_gru(), atau build_transformer())
model2 = build_bilstm()
print("\n--- Training Model ---")
history = model.fit(
    X_train, y_train,
    validation_data=(X_val, y_val),
    epochs=100,
    batch_size=32,
    class_weight=class_weights,
    callbacks=[early_stopping],
    verbose=1
)

early_stopping = EarlyStopping(monitor='val_pr_auc', mode='max', patience=15, restore_best_weights=True)

# Ganti dengan model pilihan (build_lstm(), build_bilstm(), build_gru(), atau build_transformer())
model3 = build_gru()
print("\n--- Training Model ---")
history = model.fit(
    X_train, y_train,
    validation_data=(X_val, y_val),
    epochs=100,
    batch_size=32,
    class_weight=class_weights,
    callbacks=[early_stopping],
    verbose=1
)

early_stopping = EarlyStopping(monitor='val_pr_auc', mode='max', patience=15, restore_best_weights=True)

# Ganti dengan model pilihan (build_lstm(), build_bilstm(), build_gru(), atau build_transformer())
model4 = build_transformer()
print("\n--- Training Model ---")
history = model.fit(
    X_train, y_train,
    validation_data=(X_val, y_val),
    epochs=100,
    batch_size=32,
    class_weight=class_weights,
    callbacks=[early_stopping],
    verbose=1
)

"""# Evaluation"""

# ==========================================
# 9. EVALUATION (MULTI-MODEL COMPARISON)
# ==========================================
# Asumsi Anda telah menyimpan model-model yang dilatih ke dalam variabel terpisah.
# Jika nama variabel model Anda berbeda, silakan sesuaikan dictionary di bawah ini:
models = {
    'LSTM': model,          # Sesuaikan dengan variabel model LSTM Anda
    'BiLSTM': model2,      # Sesuaikan dengan variabel model BiLSTM Anda
    'GRU': model3,            # Sesuaikan dengan variabel model GRU Anda
    'Transformer': model4
}

evaluation_results = []

print("--- Memulai Evaluasi Multi-Model ---\n")

for name, m in models.items():
    print(f"Evaluating {name}...")

    # Prediksi probabilitas
    y_pred_prob = m.predict(X_test, verbose=0)

    # Prediksi kelas dengan threshold standar 0.5
    y_pred = (y_pred_prob >= 0.5).astype(int)

    # Ekstrak nilai ROC-AUC dan PR-AUC
    roc_auc = roc_auc_score(y_test, y_pred_prob)
    pr_auc = average_precision_score(y_test, y_pred_prob)

    # Gunakan parameter output_dict=True untuk mengambil nilai metrik secara spesifik
    report = classification_report(y_test, y_pred, output_dict=True, zero_division=0)

    # Simpan hasil metrik (Fokus pada metrik kelas '1' yaitu PHA = Yes)
    evaluation_results.append({
        'Model': name,
        'Accuracy': report['accuracy'],
        'Precision (PHA=Y)': report['1']['precision'],
        'Recall (PHA=Y)': report['1']['recall'],
        'F1-Score (PHA=Y)': report['1']['f1-score'],
        'ROC-AUC': roc_auc,
        'PR-AUC': pr_auc
    })

# Konversi list hasil menjadi Pandas DataFrame
df_results = pd.DataFrame(evaluation_results)

# Tampilkan tabel dengan menyorot (highlight) nilai tertinggi di setiap kolom metrik
styled_table = df_results.style.format({
    'Accuracy': '{:.4f}',
    'Precision (PHA=Y)': '{:.4f}',
    'Recall (PHA=Y)': '{:.4f}',
    'F1-Score (PHA=Y)': '{:.4f}',
    'ROC-AUC': '{:.4f}',
    'PR-AUC': '{:.4f}'
}).highlight_max(color='lightgreen', subset=[
    'Accuracy', 'Precision (PHA=Y)', 'Recall (PHA=Y)', 'F1-Score (PHA=Y)', 'ROC-AUC', 'PR-AUC'
])

print("\n--- Tabel Perbandingan Metrik Evaluasi (Threshold 0.5) ---")
display(styled_table)

import tensorflow as tf
tf.get_logger().setLevel('ERROR') # Mematikan warning retracing agar rapi

models = {
    'LSTM': model,
    'BiLSTM': model2,
    'GRU': model3,
    'Transformer': model4
}

evaluation_results = []

print("--- Memulai Evaluasi Multi-Model (Dengan Optimasi Threshold) ---\n")

for name, m in models.items():
    print(f"Evaluating {name}...")

    # Prediksi probabilitas
    y_pred_prob = m.predict(X_test, verbose=0)

    # Metrik AUC (Bebas Threshold)
    roc_auc = roc_auc_score(y_test, y_pred_prob)
    pr_auc = average_precision_score(y_test, y_pred_prob)

    # Cari Threshold paling optimal berdasarkan F1-Score
    precisions, recalls, thresholds = precision_recall_curve(y_test, y_pred_prob)
    fscore = (2 * precisions * recalls) / (precisions + recalls + 1e-8)

    # Ambil index threshold terbaik
    best_ix = np.argmax(fscore)

    # Karena array thresholds ukurannya len(precisions)-1, kita lakukan safety check
    best_threshold = thresholds[best_ix] if best_ix < len(thresholds) else 0.5

    # Prediksi ulang menggunakan Threshold Optimal
    y_pred_opt = (y_pred_prob >= best_threshold).astype(int)

    # Ambil metrik performa akhir
    report = classification_report(y_test, y_pred_opt, output_dict=True, zero_division=0)

    evaluation_results.append({
        'Model': name,
        'Best Threshold': best_threshold,
        'Accuracy': report['accuracy'],
        'Precision (PHA=Y)': report['1']['precision'],
        'Recall (PHA=Y)': report['1']['recall'],
        'F1-Score (PHA=Y)': report['1']['f1-score'],
        'ROC-AUC': roc_auc,
        'PR-AUC': pr_auc
    })

# Render Tabel
df_results = pd.DataFrame(evaluation_results)

styled_table = df_results.style.format({
    'Best Threshold': '{:.4f}',
    'Accuracy': '{:.4f}',
    'Precision (PHA=Y)': '{:.4f}',
    'Recall (PHA=Y)': '{:.4f}',
    'F1-Score (PHA=Y)': '{:.4f}',
    'ROC-AUC': '{:.4f}',
    'PR-AUC': '{:.4f}'
}).highlight_max(color='lightgreen', subset=[
    'Accuracy', 'Precision (PHA=Y)', 'Recall (PHA=Y)', 'F1-Score (PHA=Y)', 'ROC-AUC', 'PR-AUC'
])

print("\n--- Tabel Perbandingan Metrik Evaluasi (Threshold Optimal per Model) ---")
display(styled_table)

"""# Threshold Optimization"""

precisions, recalls, thresholds = precision_recall_curve(y_test, y_pred_prob)

fscore = (2 * precisions * recalls) / (precisions + recalls + 1e-8)
best_ix = np.argmax(fscore)
best_threshold = thresholds[best_ix]

print(f"\n--- Optimal Threshold: {best_threshold:.4f} ---")
y_pred_opt = (y_pred_prob >= best_threshold).astype(int)
print(confusion_matrix(y_test, y_pred_opt))
print(classification_report(y_test, y_pred_opt))

"""# EAI"""

background_data = X_train[:100]
test_samples = X_test[:30]

explainer = shap.GradientExplainer(model, background_data)
shap_values = explainer.shap_values(test_samples)

# Memipihkan data 3D menjadi 2D (dirata-ratakan sepanjang urutan waktu) agar dapat di-plot
shap_values_2d = shap_values[0].mean(axis=1) if isinstance(shap_values, list) else shap_values.mean(axis=1)
X_test_2d = test_samples.mean(axis=1)

print("\n--- Generating SHAP Summary Plot ---")
shap.summary_plot(shap_values_2d, X_test_2d, feature_names=numerical_cols)

# ==========================================
# 11. EXPLAINABLE AI (SHAP UNTUK SEMUA MODEL)
# ==========================================
import shap
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf

# Matikan warning TF agar output rapi
tf.get_logger().setLevel('ERROR')

print("--- Memulai Analisis Explainable AI (SHAP) Multi-Model ---")
print("Peringatan: Proses ini mungkin memakan waktu beberapa menit...\n")

# 1. Ambil sampel Background Data
# Kita kurangi menjadi 50 sampel agar RAM aman saat me-loop 4 model
np.random.seed(42)
bg_indices = np.random.choice(X_train.shape[0], size=50, replace=False)
background_data = X_train[bg_indices]

test_samples = X_test

# 2. Looping untuk setiap model yang ada di dictionary 'models'
for name, m in models.items():
    print(f"[{name}] Menghitung SHAP values...")
    try:
        # Inisialisasi Explainer
        explainer = shap.GradientExplainer(m, background_data)
        shap_values = explainer.shap_values(test_samples)

        # Penanganan Dimensi List dari output Keras
        if isinstance(shap_values, list):
            shap_values_3d = shap_values[0]
        else:
            shap_values_3d = shap_values

        # Rata-ratakan terhadap waktu (axis=1) untuk plot 2D
        shap_values_2d = shap_values_3d.mean(axis=1)
        X_test_2d = test_samples.mean(axis=1)

        # Visualisasi Plot
        plt.figure(figsize=(9, 5))
        plt.title(f"SHAP Summary Plot - Model: {name}", pad=20, fontsize=14, fontweight='bold')

        shap.summary_plot(
            shap_values_2d,
            X_test_2d,
            feature_names=numerical_cols,
            plot_type='dot',
            show=False
        )
        plt.tight_layout()
        plt.show()

    except Exception as e:
        # Arsitektur kustom (seperti MultiHeadAttention di Transformer)
        # kadang tidak didukung oleh GradientExplainer standar.
        print(f"⚠️ Gagal memproses visualisasi SHAP untuk {name}.")
        print(f"Pesan Error: {e}\n")

